apply:
	terraform apply -auto-approve

login:
	@waypoint login -server-tls-skip-verify=true -from-kubernetes -from-kubernetes-namespace=waypoint -from-kubernetes-service=waypoint-ext

init:
	waypoint init

up:
	waypoint up