Vagrant.configure('2') do |config|
  config.vm.boot_timeout = 60
  config.vm.box = "vagrant-box"
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 2048
  end
  (1..3).each do |i|
    config.vm.define "node#{i}" do |n|
      n.vm.hostname = "node#{i}"
      n.vm.provision "shell", path: "provision.sh"
      n.vm.network "private_network", ip: "192.168.56.#{78 + i - 1}"
      n.vm.synced_folder "~/.nomad-k3s/", "/home/vagrant/.nomad-k3s/", create: true
      if i == 1
        n.vm.network "forwarded_port", guest: 8200, host: 8200
        n.vm.network "forwarded_port", guest: 8500, host: 8500
        n.vm.network "forwarded_port", guest: 4646, host: 4646
        n.vm.network "forwarded_port", guest: 6443, host: 6443
        n.vm.network "forwarded_port", guest: 9200, host: 9200
        n.vm.network "forwarded_port", guest: 9300, host: 9300
        n.vm.network "forwarded_port", guest: 9701, host: 9701
        n.vm.network "forwarded_port", guest: 9702, host: 9702
      end
    end
  end
end