apiVersion: v1
kind: Service
metadata:
  name: boundary-controller
  labels:
    app: boundary-controller
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: api
    name: api
  - port: 9201
    targetPort: cluster
    name: cluster
  selector:
    app: boundary-controller
---
apiVersion: v1
kind: Service
metadata:
  name: boundary-worker
  labels:
    app: boundary-worker
spec:
  type: LoadBalancer
  ports:
  - port: 9202
    targetPort: data
    name: data
  selector:
    app: boundary-worker